// Generated by CoffeeScript 1.8.0

/*
  Array
 */

(function() {
  var HttpHeader, address, body, desObj, firstThree, foreachFn, header, item, key, list, myArray, myObj, name, obj, range, result, status, value, _fn, _i, _j, _k, _l, _len, _len1, _len2, _ref, _ref1, _ref2, _ref3, _results,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  list = [1, 2, 3, 4, 5];

  range = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  [].splice.apply(range, [0, 2].concat(_ref = ['p', 'w'])), _ref;

  firstThree = ['a', 'b', 'c', 'd'].slice(0, 2);

  if (__indexOf.call(firstThree, 'g') < 0) {
    console.log('found it in array');
  }

  foreachFn = function(item) {
    return item + 'kkk';
  };

  for (_i = 0, _len = firstThree.length; _i < _len; _i++) {
    item = firstThree[_i];
    foreachFn(item);
  }

  _fn = function(item) {
    console.log(item + 'Kilogram and s');
  };
  for (key = _j = 0, _len1 = firstThree.length; _j < _len1; key = ++_j) {
    item = firstThree[key];
    _fn(item);
  }

  result = (function() {
    var _k, _len2, _results;
    _results = [];
    for (_k = 0, _len2 = firstThree.length; _k < _len2; _k++) {
      item = firstThree[_k];
      _results.push(item.name);
    }
    return _results;
  })();

  console.log('first three' + firstThree);

  HttpHeader = [
    200, {
      'Content-Type': 'text/json'
    }, 'status OK'
  ];

  status = HttpHeader[0], header = HttpHeader[1], body = HttpHeader[2];

  console.log("Header: " + header['Content-Type'] + " Status: " + status + " Body: " + status);

  myArray = (function() {
    _results = [];
    for (_k = 1; _k <= 33; _k++){ _results.push(_k); }
    return _results;
  }).apply(this);

  [].splice.apply(myArray, [2, 2].concat(_ref1 = ['a', 'b'])), _ref1;

  console.log(myArray.join(', '));

  [].splice.apply(myArray, [2, (-1) - 2 + 1].concat(_ref2 = ['k', 'j'])), _ref2;

  console.log(myArray.join(', '));

  desObj = {
    name: 'peter',
    contact: {
      address: 'central',
      phone: '11212121'
    }
  };

  console.log(desObj);

  name = desObj.name, (_ref3 = desObj.contact, address = _ref3.address);

  console.log("Destructive Assignment name: " + name + " contact-address: " + address);

  myArray = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

  for (key = _l = 0, _len2 = myArray.length; _l < _len2; key = _l += 2) {
    value = myArray[key];
    console.log("Some Key: " + key + " Value: " + value);
  }

  myObj = {
    a: 1,
    b: 2,
    c: 3,
    d: 4
  };

  for (key in myObj) {
    obj = myObj[key];
    console.log("Object value: " + obj);
  }

}).call(this);

//# sourceMappingURL=array.js.map
