// Generated by CoffeeScript 1.8.0
(function() {
  var myArray, myNewArray, value;
  myArray = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

  myNewArray = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = myArray.length; _i < _len; _i++) {
      value = myArray[_i];
      _results.push(value * 2);
    }
    return _results;
  })();

  console.log(myNewArray);

}).call(this);

//# sourceMappingURL=iteration.js.map
